#!/bin/bash
clear
echo "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
echo ""
echo "$(tput setaf 1)$(tput bold)RAWS COMMAND LIST$(tput sgr0)"

echo "1. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)-v $(tput sgr0)"

echo "2. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)sysinfo $(tput sgr0)"

echo "3. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)inode $(tput sgr0)"

echo "4. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)acreate $(tput sgr0)"

echo "5. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)install apache $(tput sgr0)"

echo "6. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)install raw-os $(tput sgr0)"

echo "7. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)update $(tput sgr0)"

echo "8. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)help $(tput sgr0)"

echo ""
echo "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
echo "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
echo ""
echo "$(tput setaf 1)$(tput bold)WHAT COMMANDS DO!$(tput sgr0)"

echo "1. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)-v $(tput sgr0) $(tput setaf 2)-------------| Show Version$(tput sgr0)"

echo "2. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)sysinfo $(tput sgr0) $(tput setaf 2)--------| Show System Info$(tput sgr0)"

echo "3. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)inode $(tput sgr0) $(tput setaf 2)----------| Install Nodejs$(tput sgr0)"

echo "4. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)acreate $(tput sgr0) $(tput setaf 2)--------| Create Apache Vhost$(tput sgr0)"

echo "5. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)install apache $(tput sgr0) $(tput setaf 2)-| Install Apache+php$(tput sgr0)"

echo "6. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)install raw-os $(tput sgr0) $(tput setaf 2)-| Install Gnome Desk.$(tput sgr0)"

echo "7. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)update $(tput sgr0) $(tput setaf 2)---------| Update The-Raw$(tput sgr0)"

echo "8. $(tput setaf 2) raws$(tput sgr0) $(tput setaf 1)help $(tput sgr0) $(tput setaf 2)-----------| Read This Page.$(tput sgr0)"

echo ""
echo "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
