#!/bin/bash
echo -n "Updating System..."; apt-get update -y  &>/dev/null; echo "Done.";
echo -n "Upgrading System..."; apt-get upgrade -y  &>/dev/null; echo "Done.";
echo -n "Installing Apache..."; apt-get install apache2 -y   &>/dev/null; echo "Done.";
service apache2 start
apt-get install php5 -y
service apache2 restart
apt-get install -y libapache2-mod-php5 php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-ming php5-ps
apt-get install -y php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl

service apache2 restart
sudo php5enmod mcrypt 
sudo a2enmod rewrite 
service apache2 restart 
sleep 3
clear
mkdir /hostdata/
chmod -R 755 /hostdata/
m='
<Directory /hostdata/>
         Options Indexes FollowSymLinks
         AllowOverride None
         Require all granted
</Directory>
'
echo "$m" >> /etc/apache2/apache2.conf
service apache2 restart

#Installing Mysql.
cd ~/
apt-get update
apt-get install expect -y

VAR=$(expect -c '
spawn apt-get install mysql-server -y
expect "New password for the MySQL \"root\" user:"
send "root\r"
expect "Repeat password for the MySQL \"root\" user:"
send "root\r"
expect eof
')
echo "$VAR"
apt-get install mysql-client libmysqlclient15-dev -y
clear
/etc/init.d/mysql stop
/etc/init.d/mysql start
sleep 3
clear

#Installing PhpMyAdmin.
cd ~/
apt-get install pwgen -y

MYSQL_ROOT_PASS="root"

PHPMYADMIN_DIR="mysql"
                                   
AUTOGENERATED_PASS=`pwgen -c -1 20`

echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections

apt-get install phpmyadmin -y
clear
# Regex FTW!
sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf
clear
php5enmod mcrypt
clear
service apache2 reload
sleep 0.5
clear
echo -e "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
echo -e "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
echo -e "U'r Vhost Folder Is /hostdata/"
echo -e "Mysql User : root "
echo -e "Mysql Passwd : root "
echo -e "Please Change Mysql Root Passwd"
echo -e "Phpmyadmin : yourdomain/mysql"
echo -e "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
echo -e "*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*"
