#!/usr/bin/env bash

apt-get install pwgen -y

MYSQL_ROOT_PASS="root"

PHPMYADMIN_DIR="mysql"
                                   
AUTOGENERATED_PASS=`pwgen -c -1 20`

echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections

apt-get install phpmyadmin -y
clear
# Regex FTW!
sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf
clear
php5enmod mcrypt
clear
service apache2 reload
sleep 2
clear
rm -Rf ~/sqladmin.sh
